# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_history: # create an artifact from the existing documentation builds
    runs-on: ubuntu-latest
    steps:
      - name: get the gh-pages repo
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: tar the existing docs
        run: |
          mkdir -p ./docs
          tar -cvf documentation.tar ./docs

      - name: create a document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: documentation.tar
  # This workflow contains a single job called "build"
  build:
    needs: get_history
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout src
        uses: actions/checkout@v4

      - run: mkdir -p ./docs
      - name: Download the existing documents artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
      - run: tar -xf documentation.tar ./docs -C ./docs

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: npm install, build, and test
        run: |
          npm -g i pnpm@8
          pnpm install
          pnpm run docs
          node ./scripts/versions.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
